apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - 01-eks-serviceaccounteks-patch.yml
  - 02-virtual-service-patch.yml
  - 03-configmaps-patch.yml
  - 06-deployment-patch.yml

# Patch ECR image to pull from
images:
  - name: 250412402401.dkr.ecr.us-east-1.amazonaws.com
    newName: 250412402401.dkr.ecr.us-east-1.amazonaws.com/ms-facade-devetel-configs-release
    newTag: ${NEW_TAG}
